version: '3.8'

services:
  fastapi:
    build: .
    container_name: app-fsl
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000